import { useMemo,useState } from 'react'
import { Bell, Search, ChevronDown, UserRound, Settings, LogOut, Menu, X } from 'lucide-react'
import { useLocation } from 'react-router-dom'
import { navigateTo } from '@/app/router/navigation'
import { employees } from '@/features/employees/data/employeesData'
import { useAuth } from '@/app/providers/use-auth'
import Sidebar from './Sidebar'

export default function Header(){const {pathname}=useLocation();const [query,setQuery]=useState('');const [open,setOpen]=useState(false);const [notify,setNotify]=useState(false);const [mobile,setMobile]=useState(false);const {user,signOut}=useAuth();const title=pathname.split('/').filter(Boolean).at(-1)?.replace(/-/g,' ')||'Dashboard';const results=useMemo(()=>employees.filter(e=>`${e.firstName} ${e.lastName} ${e.id} ${e.dept} ${e.title}`.toLowerCase().includes(query.toLowerCase())).slice(0,5),[query]);
return <><div className="topbar"><button className="icon-button menu-toggle" onClick={()=>{if(window.matchMedia('(max-width: 1100px)').matches)setMobile(!mobile);else window.dispatchEvent(new Event('hrm:sidebar-toggle'))}} aria-label="Toggle navigation">{mobile?<X size={18}/>:<Menu size={18}/>}</button><div className="crumbs"><span>Workspace</span><b>/</b><strong>{title}</strong></div><div className="topbar-right"><div className="global-search"><Search size={16}/><input aria-label="Search employees" placeholder="Search anything..." value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd>{query&&<div className="search-results">{results.map(e=><button key={e.id} onClick={()=>{setQuery('');navigateTo(`/app/employees/${e.id}`)}}><span className="avatar-mini">{e.firstName[0]}{e.lastName[0]}</span><span>{e.firstName} {e.lastName}<small>{e.id} · {e.dept}</small></span></button>)}{!results.length&&<p>No matching employees</p>}</div>}</div><div className="menu-wrap"><button className="icon-button notification-button" aria-label="Notifications" onClick={()=>setNotify(!notify)}><Bell size={18}/><i/></button>{notify&&<div className="pop-menu"><b>Notifications</b><p>You're all caught up.</p></div>}</div><div className="menu-wrap"><button className="profile-trigger" onClick={()=>setOpen(!open)}><span className="profile-avatar">{user?.name?.split(' ').map(x=>x[0]).join('').slice(0,2)||'JD'}</span><span className="profile-name">{user?.name||'Jane Doe'}<small>{user?.role||'HR Administrator'}</small></span><ChevronDown size={15}/></button>{open&&<div className="pop-menu user-menu"><button onClick={()=>navigateTo('/app/settings')}><UserRound size={15}/> Profile</button><button onClick={()=>navigateTo('/app/settings')}><Settings size={15}/> Settings</button><button onClick={()=>{signOut();navigateTo('/login')}}><LogOut size={15}/> Sign out</button></div>}</div></div></div>{mobile&&<div className="mobile-drawer"><Sidebar/></div>}</>}
